### ISSUE TITLE
AudioDevicePort cannot find symbol class

### ISSUE THREAD

**Issue by anudeepdivami** [sonyxperiadev/packages-apps-FMRadio#5]
Hey,

Thanks a ton for sharing this. But for some reason, I am unable to use this. I am using Android Studio with compile version 25 and FmServive.java throws a set of error while building the application. Most of them say it cannot find symbol like the above. Can you please heal me what might the root cause be. 

Thanks in advance.

**Comment by jerpelea** [comment]
the code compiles fine in the android tree and it is not intended to be compiled as a standalone app

**Comment by anudeepdivami** [comment]
Hey,

Thanks a lot for your quick reply. I'm new to development. Can you please provide me with a link that can help me compile in Android tree.

**Comment by anudeepdivami** [comment]
Also can you please let me know if this works only on a rooted device? Thank you.

**Comment by jerpelea** [comment]
our website should provide all the information 
https://developer.sonymobile.com/open-devices/

**Comment by bartcubbins** [comment]
@jerpelea solved
